#
# Pull from GitHub source repository
#
stages:
  - github-pull

before_script:
  - git --version

after_script:
  - git log -5 --oneline --pretty=format:'\''%C(yellow)%h %C(reset)[%C(green)%aN,%C(reset) %C(cyan)%ad%C(reset)] %s'\'' --date=format:'\''%d.%m.%y %H:%M'\''

do-pull:
  stage: github-pull
  image: 
    name: alpine/git
    entrypoint: [""]
  tags:
  - docker
  # only:
  # - schedules
  script:
  - git remote -v

